### ISSUE TITLE
Fix Earthly/Dockerfile dichotomy

### ISSUE THREAD

**Issue by Bckempa** [space-ros/space-ros#107]
Currently some components use Earthly Earthfiles while others use Dockerfiles. Get everything within the same ecosystem.

On one hand, removing Earthly means more engineering work to replace the scripting and dependency resolution it currently provides. On the other, moving everything back to plain Docker/Make/Shell might be more familiar to most contributors.

- [x] space-ros/docker#156
  - [x] space-ros/space-ros#159
  - [ ] space-ros/docker#142 (will serve as a template for issues below)
    - [x] space-ros/space-ros#161
    -  [ ] space-ros/demos#27
    -  [ ] space-ros/demos#28
    - [ ] space-ros/docs#46
- [ ] space-ros/space-ros#160

Issues on the same level can be executed in parallel. Levels outline dependencies (e.g. 159 depends on 158, and 161 depends on 142)

**Comment by asimonov** [comment]
> Personally I'm in favor of migrating away from Earthly, I think it's too niche for an unfunded OSS project to rely on contributors to know.
> 
> Also, there's such massive room for improvement in the Dockerfiles and the Docker syntax included in the Earthfiles that we need to be more focused on supporting one system.

I was thinking the same before I took time to understand Earthly. Now I think it is better to stick with Earthly :). 

Or we can keep space-ros on Earthly and use Docker for demos until it gets too complex, then convert those to Earthly? I.e. the current approach :)
