### ISSUE TITLE
Adjust main spaceros image to the new build approach

### ISSUE THREAD

**Issue by EzraBrooks** [space-ros/space-ros#177]
See discussion https://github.com/space-ros/space-ros/discussions/140 and issue https://github.com/space-ros/space-ros/issues/107 for more context

TODOs:
- [x] space-ros/space-ros#172
- [x] space-ros/docker#156
- [x] space-ros/space-ros#174
- [x] space-ros/space-ros#175
- [x] space-ros/space-ros#176
- [ ] To figure out - final naming convs or base and dev images
- [ ] Decide if we want to push base image to docker hub
- [ ] Document both images in README

The proposed modified version of generate_repos.sh https://gist.github.com/xfiderek/e07e02930d58c05807208dee2742d9a1

**Comment by ivanperez-keera** [comment]
Closed in favor of existing issue #186 and other issues already solved.
