### ISSUE TITLE
Enable SARIF output for all Code Analysis Tools

### ISSUE THREAD

**Issue by mjeronimo** [space-ros/space-ros#24]
- [x] https://github.com/space-ros/space-ros/issues/13
- [x] https://github.com/space-ros/space-ros/issues/17
- [x] https://github.com/space-ros/space-ros/issues/18
- [x] https://github.com/space-ros/space-ros/issues/19
- [x] https://github.com/space-ros/space-ros/issues/20
- [x] https://github.com/space-ros/space-ros/issues/21
- [x] https://github.com/space-ros/space-ros/issues/22
